### ISSUE TITLE
Doku not showing any anything - Error in log

### ISSUE THREAD

**Issue by cobalt027** [amerkurev/doku#22]
Hello!
I'm running this in unraid 6.11.5 with the template from the AppCenter.
I'm seeing this in the logs for Doku:
time="2023-07-16T12:05:57-04:00" level=error msg="failed to execute request: docker disk usage" err="Error response from daemon: a disk usage operation is already running"

What have I done wrong?

**Comment by ewoks** [comment]
+1 for the same running in container on Synology

**Comment by bedelaitre** [comment]
It seems that DOKU doesn't support reverse proxy using HTTPS.

My reverse proxu is "https://app.xxxxx.synology.me", with HTTPS.

In the log file (with log set to debug), I can see references to http://app.xxxxx.synology.me (with HTTP)

`time="2024-02-21T14:33:21Z" level=debug msg="request started" http_method=GET http_proto=HTTP/1.1 http_scheme=http remote_addr=192.54.200.178 ts="Wed, 21 Feb 2024 14:33:21 UTC" uri="http://app.xxxxx.synology.me/v0/disk-usage" user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0"`

**Comment by cobalt027** [comment]
I have it running on 2 unraid servers. One using the default docker vdisk (not working) the other is using the docker directories (working). Is it possible that the unraid docker vdisk is messing it up?

**Comment by amerkurev** [comment]
Hey! I released a new Doku version (1.0.0), try it out! Hopefully, it fixes some issues, but no promises. 😅

**Comment by cobalt027** [comment]
> Hey! I released a new Doku version (1.0.0), try it out! Hopefully, it fixes some issues, but no promises. 😅

Yeah, I saw that. I was all excited. 
I'm seeing this in my logs:
INFO:     Uvicorn running on http://0.0.0.0:9090 (Press CTRL+C to quit)
2025-03-12 07:43:53,612 WARN exited: df-scanner (exit status 1; not expected)
2025-03-12 07:44:29,534 WARN received SIGTERM indicating exit request
2025-03-12 07:44:29,716 WARN stopped: uvicorn (terminated by SIGTERM)
Revision: v1.0.0-88bc232
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/usr/local/lib/python3.13/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/usr/local/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/app/scan/df.py", line 41, in <module>
    main()  # pragma: no cover
    ~~~~^^
  File "/usr/src/app/scan/df.py", line 24, in main
    scanner.scan()  # run once immediately
    ~~~~~~~~~~~~^^
  File "/usr/src/app/scan/scanner.py", line 75, in scan
    data = self.client.df()
  File "/usr/local/lib/python3.13/site-packages/docker/client.py", line 189, in df
    return self.api.df()
           ~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/docker/utils/decorators.py", line 32, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/docker/api/daemon.py", line 22, in df
    return self._result(self._get(url), True)
                        ~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/site-packages/docker/utils/decorators.py", line 44, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/docker/api/client.py", line 246, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2025-03-12 16:56:34,646 WARN exited: df-scanner (exit status 1; not expected)
INFO:     DF scanner started (system df + logfiles).

Any suggestions?

**Comment by amerkurev** [comment]
Oops! How did that happen? 😅 Could you please share how you started the container? I see that localhost is being used as the Docker host, and the port is set to None. However, the default parameters are unix:///var/run/docker.sock. So, I don’t quite understand how localhost could have been used instead.

**Comment by cobalt027** [comment]
This is how unraid starts the container:
docker run
  -d
  --name='Doku'
  --net='bridge'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Kobe"
  -e HOST_CONTAINERNAME="Doku"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:9090]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/amerkurev/doku/master/web/doku/public/favicon.ico'
  -p '9099:9090/tcp'
  -v '/var/run/docker.sock':'/var/run/docker.sock':'ro'
  -v '/mnt/user':'/hostroot/mnt/user':'ro'
  -v '/var/lib/docker/':'/hostroot/var/lib/docker/':'ro' 'amerkurev/doku'
a400ca1bc8fec31c2af1e7f47b857314ada38c42bab992ca0a6b1f336bdf4675

**Comment by amerkurev** [comment]
I finally figured out what happened! Your 'df' command takes a long time to execute (more than 60 seconds). The default timeout is triggered. You need to increase the timeout value by setting the DOCKER_TIMEOUT environment variable. For example, like this: DOCKER_TIMEOUT=600 (10 minutes).

**Comment by jo-chemla** [comment]
I've been facing the same errors with Doku running via docker-compose on a NAS with a few dozen containers and 100TBs volume. 
Is it possible to deactivate `df` - or rely on other disk-usage utilities, like [ncdu](https://dev.yorhel.nl/ncdu) or [duc](https://github.com/zevv/duc) which are said to execute faster?

**Comment by amerkurev** [comment]
Closing as a duplicate of #53 — the issue was resolved there.

**Comment by famschouenberg** [comment]
I can confirm that update has resolved the issue, thanks!
